add web-app/servlet/0/servlet-name cofaxCDS
add web-app/servlet/0/servlet-class org.cofax.cds.CDSServlet
add web-app/servlet/0/init-param/configGlossary:installationAt "Philadelphia, PA"
add web-app/servlet/0/init-param/configGlossary:adminEmail ksm@pobox.com
add web-app/servlet/0/init-param/configGlossary:poweredBy Cofax
add web-app/servlet/0/init-param/configGlossary:poweredByIcon /images/cofax.gif
add web-app/servlet/0/init-param/configGlossary:staticPath /content/static
add web-app/servlet/0/init-param/templateProcessorClass org.cofax.WysiwygTemplate
add web-app/servlet/0/init-param/templateLoaderClass org.cofax.FilesTemplateLoader
add web-app/servlet/0/init-param/templatePath templates
add web-app/servlet/0/init-param/templateOverridePath
add web-app/servlet/0/init-param/defaultListTemplate listTemplate.htm
add web-app/servlet/0/init-param/defaultFileTemplate articleTemplate.htm
add web-app/servlet/0/init-param/useJSP false
add web-app/servlet/0/init-param/jspListTemplate listTemplate.jsp
add web-app/servlet/0/init-param/jspFileTemplate articleTemplate.jsp
add web-app/servlet/0/init-param/cachePackageTagsTrack 200
add web-app/servlet/0/init-param/cachePackageTagsStore 200
add web-app/servlet/0/init-param/cachePackageTagsRefresh 60
add web-app/servlet/0/init-param/cacheTemplatesTrack 100
add web-app/servlet/0/init-param/cacheTemplatesStore 50
add web-app/servlet/0/init-param/cacheTemplatesRefresh 15
add web-app/servlet/0/init-param/cachePagesTrack 200
add web-app/servlet/0/init-param/cachePagesStore 100
add web-app/servlet/0/init-param/cachePagesRefresh 10
add web-app/servlet/0/init-param/cachePagesDirtyRead 10
add web-app/servlet/0/init-param/searchEngineListTemplate forSearchEnginesList.htm
add web-app/servlet/0/init-param/searchEngineFileTemplate forSearchEngines.htm
add web-app/servlet/0/init-param/searchEngineRobotsDb WEB-INF/robots.db
add web-app/servlet/0/init-param/useDataStore true
add web-app/servlet/0/init-param/dataStoreClass org.cofax.SqlDataStore
add web-app/servlet/0/init-param/redirectionClass org.cofax.SqlRedirection
add web-app/servlet/0/init-param/dataStoreName cofax
add web-app/servlet/0/init-param/dataStoreDriver com.microsoft.jdbc.sqlserver.SQLServerDriver
add web-app/servlet/0/init-param/dataStoreUser sa
add web-app/servlet/0/init-param/dataStorePassword dataStoreTestQuery
add web-app/servlet/0/init-param/dataStoreLogFile /usr/local/tomcat/logs/datastore.log
add web-app/servlet/0/init-param/dataStoreInitConns 10
add web-app/servlet/0/init-param/dataStoreMaxConns 100
add web-app/servlet/0/init-param/dataStoreConnUsageLimit 100
add web-app/servlet/0/init-param/dataStoreLogLevel debug
add web-app/servlet/0/init-param/maxUrlLength 500
add web-app/servlet/1/servlet-name cofaxEmail
add web-app/servlet/1/servlet-class org.cofax.cds.EmailServlet
add web-app/servlet/1/init-param/mailHost mail1
add web-app/servlet/1/init-param/mailHostOverride mail2
add web-app/servlet/2/servlet-name cofaxAdmin
add web-app/servlet/2/servlet-class org.cofax.cds.AdminServlet
add web-app/servlet/3/servlet-name fileServlet
add web-app/servlet/3/servlet-class org.cofax.cds.FileServlet
add web-app/servlet/4/servlet-name cofaxTools
add web-app/servlet/4/servlet-class org.cofax.cms.CofaxToolsServlet
add web-app/servlet/4/init-param/templatePath toolstemplates/
add web-app/servlet/4/init-param/log 1
add web-app/servlet/4/init-param/logLocation /usr/local/tomcat/logs/CofaxTools.log
add web-app/servlet/4/init-param/logMaxSize
add web-app/servlet/4/init-param/dataLog 1
add web-app/servlet/4/init-param/dataLogLocation /usr/local/tomcat/logs/dataLog.log
add web-app/servlet/4/init-param/dataLogMaxSize
add web-app/servlet/4/init-param/fileTransferFolder /usr/local/tomcat/webapps/content/fileTransferFolder
add web-app/servlet/4/init-param/lookInContext 1
add web-app/servlet/4/init-param/adminGroupID 4
add web-app/servlet/4/init-param/betaServer true
add web-app/servlet-mapping/cofaxCDS /
add web-app/taglib/taglib-uri cofax.tld
add web-app/taglib/taglib-location /WEB-INF/tlds/cofax.tld
