package golem:component;

// For more details about the WIT syntax, see
// https://github.com/WebAssembly/component-model/blob/main/design/mvp/WIT.md

// naming is a little odd, because these map directly to cli commands,
// and there, it's a PITA to type unnecessary - and _
interface api {
  add: func(path: string, value: string);
  get: func(path: string) -> option<string>;
  listpaths: func() -> list<string>;
  addtree: func(path: string, json: string) -> result<_,string>;
  // fetch an entire subtree rooted at path
  gettree: func(path: string) -> option<string>;
  delete: func(path: string);
  drop: func();
}

world slkvs {
  export api;
}
