package golem:component;

// See https://github.com/WebAssembly/component-model/blob/main/design/mvp/WIT.md for more details about the WIT syntax

interface api {
  add: func(path: string, value: string);
  get: func(path: string) -> option<string>;
}

world yoyo {
  export api;
}
