package golem:component;

// See https://github.com/WebAssembly/component-model/blob/main/design/mvp/WIT.md for more details about the WIT syntax

interface api {
  add: func(path: string, value: string);
  get: func(path: string) -> option<string>;
  listpaths: func() -> list<string>;
  addtree: func(path: string, json: string);
  delete: func(path: string);
  drop: func();
}

world yoyo {
  export api;
}
